version: "4.28.0"


services:
  mypostgres:
    image: postgres:16
    container_name: mypostgres
    networks:
      - redisnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=course1
  myredis:
    image: redis/redis-stack:latest
    container_name: myredis
    networks:
      - redisnet
    hostname: myredis
    ports:
      - "6379:6379"
      - "8001:8001"
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - redisnet
    depends_on:
      - mypostgres
      - myredis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/course1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATA_REDIS_HOST=myredis
      - SPRING_DATA_REDIS_PORT=6379

networks:
  redisnet:
    external: true