DROP TABLE IF EXISTS COMMENT;

DROP TABLE IF EXISTS POST;

CREATE TABLE POST
(
    id      SERIAL PRIMARY KEY,
    title   VARCHAR(255) NOT NULL,
    content VARCHAR(255)
);

CREATE TABLE COMMENT
(
    id      SERIAL PRIMARY KEY,
    post_id BIGINT       NOT NULL,
    content VARCHAR(255) NULL,
    created TIMESTAMP
);

ALTER TABLE COMMENT
    ADD CONSTRAINT FK_COMMENT_POST
        FOREIGN KEY (post_id) REFERENCES POST (id);